//
//  DCNSConnection-Delegate.h
//  Distributed Classes
//
//  Created by Matt Clarke on 18/11/2016.
//  Copyright © 2017 Matt Clarke. All rights reserved.
//
//  This file is part of the Distributed Classes Library and is provided
//  under the terms of the GNU Lesser General Public License.
//

#ifndef _DO_H_DCNSConnectionDelegate
#define _DO_H_DCNSConnectionDelegate

#import <Foundation/NSObject.h>

@class NSData;
@class NSArray;

@protocol DCNSConnectionDelegate <NSObject>

@required

/**
 Allows for creating authentication data to append onto a given message.
 @param components The components of the message to be sent. (Note: components[0] is the main body of the message)
 @param key A 256-bit key generated by Diffie-Hellman used for the current session.
 @return Data to be appended to the message, or [NSData data].
 */
-(nonnull NSData*)authenticationDataForComponents:(nonnull NSArray*)components andSessionKey:(nonnull char*)key;

/**
 Allows for verifying the authentication data appended by the remote to a message.
 @param components The components of the message recieved. (Note: components[0] is the main body of the message)
 @param data The authentication data appended by the remote.
 @param key A 256-bit key generated by Diffie-Hellman used for the current session.
 @return The verification result
 */
-(BOOL)authenticateComponents:(nonnull NSArray*)components withData:(nonnull NSData*)data andSessionKey:(nonnull char*)key;

/**
 Allows for providing encryption on a message. 
 @discussion Both the main body of the message AND the authentication data provided by your delegate will be subject to encryption here. It is recommended to do any message integrity checks here, such as a HMAC.
 @param plaintext The input data to encrypt from the message.
 @param key A 256-bit key generated by Diffie-Hellman used for the current session.
 @return Encrypted data to send to the remote
 */
-(nonnull NSData*)encryptData:(nonnull NSData*)plaintext andSessionKey:(nonnull char*)key;

/**
 Allows for decrypting a recieved message.
 @discussion Both the main body of the message AND the authentication data provided by your delegate will be subject to encryption here. It is recommended to do any message integrity checks here, such as a HMAC.
 @param ciphertext The input encrypted data
 @param key A 256-bit key generated by Diffie-Hellman used for the current session.
 @return Decrypted data to process
 */
-(nonnull NSData*)decryptData:(nonnull NSData*)ciphertext andSessionKey:(nonnull char*)key;

@end

#endif /* _DO_H_DCNSConnectionDelegate */
